### ISSUE TITLE
questions about equation (1) and the loss in the code

### ISSUE THREAD

**Issue by gaosh** [kridgeway/f-statistic-loss-nips-2018#1]
Hi,
Thanks for the nice paper and implementation.

In the code of loss computation, `tf.betainc` is used, which compute the integral of regularized beta function. In the paper, you mentioned that **I** in equation(1) is regularized incomplete beta function, which confused me. I think **I** in the paper is the integral of regularized incomplete beta function.

**Comment by kridgeway** [comment]
Thank you for checking out the project!

The CDF of the F-distribution is defined by the [regularized incomplete beta function](https://en.wikipedia.org/wiki/F-distribution#Definition). In [the tensorflow docs](https://www.tensorflow.org/api_docs/python/tf/math/betainc), this function is described as the "regularized incomplete beta integral", but they're the same.

**Comment by gaosh** [comment]
Thanks for the clarification!
